### ISSUE TITLE
Devdash doesn't render

### ISSUE THREAD

**Issue by trezy** [Phantas0s/devdash#3]
**Description**

I've just discovered DevDash and love the idea, so I'm trying to get it running. However, it doesn't seem to want to render. If I run it without a config I do get the message that I should use a config, but when I run _with_ a config, I just get an empty terminal.

I'm running this inside of a `tmux` pane, but I've had the same experience running from the standard terminal.

**OS**
macOS Catalina 10.15

**Install method**
[GoFish](https://gofi.sh)

**Config**
```yml
---
projects:
  - name: Fuelrats.com
    services:
      monitor:
        address: "https://fuelrats.com"
      widgets:
        - row:
          - col:
              size: "M"
              elements:
                - name: mon.box_availability
                  options:
                    border_color: green
```
