### ISSUE TITLE
gsc.table_pages not working?

### ISSUE THREAD

**Issue by tomkyle** [Phantas0s/devdash#74]
version 0.5.0 / MacOS via homebrew

It seems widget elements for _gsc.table_queries_ only show data from _gsc.table_queries_. What may be the reason?

Here the relevant YAML config, copied from the official example:

```yaml
    services:
      google_search_console:
        keyfile: "/path/to/file.json"
        address: 'https://example.com'
    widgets:
      - row:
          - col:
              size: 12
              elements:
                - name: gsc.table_queries
                  options:
                    title: " Last month queries "
                    start_date: "last_month"
                    end_date: "last_month"
                    character_limit: 25
                    row_limit: 10
                    metrics: "clicks,impressions"
                    border_color: green
                    title_color: green
                    text_color: green
      - row:
          - col:
              size: 12
              elements:
                - name: gsc.table_pages
                  options:
                    title: " Last month pages "
                    start_date: "last_month"
                    end_date: "last_month"
                    character_limit: 25
                    row_limit: 10
                    border_color: yellow
                    title_color: yellow
                    text_color: yellow
```

and the console output:
<img width="789" alt="grafik" src="https://user-images.githubusercontent.com/412560/192143495-0820ff31-e956-4726-aa7f-fae86730820f.png">

Disclaimer: I am new in this Google-Cloud-Service-Account-Credentials-Key-Json-stuff hell and feel a bit overwhelmed – so, if the reason is to be located there, any hints are appreciated.
