### ISSUE TITLE
Config example to monitor multiple resources

### ISSUE THREAD

**Issue by inktrap** [Phantas0s/devdash#8]
Currently the docs show how to monitor one resource.

```
projects:
  - name: Default dashboard located at $HOME/.config/devdash/default.yml
    services:
      monitor:
        address: "https://example.org"
    widgets:
      - row:
          - col:
              size: "M"
              elements:
                - name: mon.box_availability
                  options:
                    title: " thevaluable.dev status "
                    color: yellow
```

I would like to add multiple addresses, so maybe make monitor take a list of dicts (each dict with name, address fields?)?

**Comment by Phantas0s** [comment]
If you grab the last release (v0.4.2), you can specify the address directly in the widget:

```
projects:
  - name: Default dashboard located at $HOME/.config/devdash/default.yml
    services:
      monitor:
        address: "https://thevaluable.dev"
    widgets:
      - row:
          - col:
              size: "M"
              elements:
                - name: mon.box_availability
                  options:
                    title: " thevaluable.dev status "
                    color: yellow
                - name: mon.box_availability
                  options:
                    title: " example.com "
                    address: "https://example.com"
                    color: yellow
```

If it's fine for you don't forget to close the issue :)
